In [21]:
import numpy as np
sizes=[3,6,2]
biases = [np.random.rand(1,y) for y in sizes[1:]]
weights = [np.random.randn(y, x)
                for x, y in zip(sizes[:-1], sizes[1:])]
print(biases[0])
weights[0].dot(np.array([[10575],[36],[1643]]))

[[ 0.22267308  0.62107772  0.87053003  0.40928026  0.89081499  0.13947338]]


array([[ 10465.03702197],
       [-13727.44510677],
       [  8333.36714507],
       [   226.75782943],
       [  7466.06580812],
       [ -2421.29024384]])

In [4]:
import numpy as np

In [11]:
def cost_func(output_activations, y):
    return 0.5 * np.linalg.norm(output_activations - y)

In [13]:
np.linalg.norm(np.array([3,4]))

5.0

In [7]:
a,b = (np.random.randn(3,1),  np.random.randn(3,1))
a,b

(array([[-1.40948116],
        [ 0.49709222],
        [-0.29249697]]), array([[-0.60703968],
        [ 0.276252  ],
        [ 0.69457329]]))

In [12]:
cost_func(a,b)

0.64555991762837728